### ISSUE TITLE
React Hooks support

### ISSUE THREAD

**Issue by lfades** [lfades/next-with-apollo#31]
This issue is not to allow the usage of withApollo as a hook, because it needs to have access to `getInitialProps`, and it's a `static` method. This is to have a reminder that as soon as `react-apollo@2.3.0-beta.1` gets out the dependency needs to be updated, otherwise `getDataFromTree` will break the new react hooks. Maybe I should create a beta version of this package too.

Related to [react-apollo#2533](https://github.com/apollographql/react-apollo/pull/2533) and [react-apollo#2541](https://github.com/apollographql/react-apollo/issues/2541)

**Comment by lamtranweb** [comment]
Can you please update `react-apollo` dependency to 2.3.1 so Hooks can work again?  Thanks!

**Comment by lfades** [comment]
Sure, I will, I'm also thinking in setting react-apollo as a peer dependency.

**Comment by lamtranweb** [comment]
Peer dependency makes sense.

**Comment by lfades** [comment]
I just published a new version to address this, @lamtranweb can you try it out ?

**Comment by lamtranweb** [comment]
Worked!  Thanks!

**Comment by lfades** [comment]
Cool, now I just need to figure out why the author of my commits looks weird haha

**Comment by lkbr** [comment]
Not sure how you both got next, next-with-apollo and react-apollo working. I get errors. Any ideas?

client error: 

```
Unhandled Rejection (TypeError): Object(...) is not a function
Example
./pages/index.js:6
  3 | 
  4 | import { useState } from "react"
  5 | 
> 6 | function Example() {
  7 |   // Declare a new state variable, which we'll call "count"
  8 |   const [count, setCount] = useState(0)
  9 | 
```

server error
```
GraphQL error occurred [getDataFromTree] TypeError: Object(...) is not a function
    at Example (/Users/lukebrown/Documents/dev/next-apollo-hooks/.next/server/static/development/pages/index.js:141:73)
    at processChild (/Users/lukebrown/Documents/dev/next-apollo-hooks/node_modules/react-dom/cjs/react-dom-server.node.development.js:2790:14)
    at resolve (/Users/lukebrown/Documents/dev/next-apollo-hooks/node_modules/react-dom/cjs/react-dom-server.node.development.js:2714:5)
    at ReactDOMServerRenderer.render (/Users/lukebrown/Documents/dev/next-apollo-hooks/node_modules/react-dom/cjs/react-dom-server.node.development.
js:3098:22)
    at ReactDOMServerRenderer.read (/Users/lukebrown/Documents/dev/next-apollo-hooks/node_modules/react-dom/cjs/react-dom-server.node.development.js
:3057:29)
    at renderToStaticMarkup (/Users/lukebrown/Documents/dev/next-apollo-hooks/node_modules/react-dom/cjs/react-dom-server.node.development.js:3539:2
7)
    at process (/Users/lukebrown/Documents/dev/next-apollo-hooks/node_modules/react-apollo/react-apollo.umd.js:129:24)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

Here's a basic repo: https://github.com/lkbr/next-apollo-hooks

**Comment by lfades** [comment]
@lkbr You're using the latest release of React which doesn't have hooks, use the alpha releases instead.

**Comment by lkbr** [comment]
🤦‍♂️  Yikes. Meticulously checked I was using the latest next, next with apollo and react apollo and forgot the most obvious one. Thanks @lfades. I can confirm that was the issue.
