### ISSUE TITLE
@apollo/react-ssr does not support @apollo/client

### ISSUE THREAD

**Issue by hoangvvo** [lfades/next-with-apollo#93]
I would like to use `next-with-apollo` with the new @apollo/client in beta. However, @apollo/react-ssr would link to the no-longer-exist @apollo/react-hooks.

I found that using @apollo/react-ssr @ beta works. `next-with-apollo`, however, use the stable version which is not compatible.

How about relaxing the semver on @apollo/react-ssr or add it as a peer dep?

```
Error: Cannot find module 'apollo-client'
Require stack:
- /media/hoang/DEV/withstereo/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js
- /media/hoang/DEV/withstereo/node_modules/next-with-apollo/node_modules/@apollo/react-ssr/lib/react-ssr.cjs.js
- /media/hoang/DEV/withstereo/node_modules/next-with-apollo/lib/withApollo.js
- /media/hoang/DEV/withstereo/node_modules/next-with-apollo/lib/index.js
- /media/hoang/DEV/withstereo/.next/server/static/development/pages/_app.js
- /media/hoang/DEV/withstereo/node_modules/next/dist/next-server/server/load-components.js
- /media/hoang/DEV/withstereo/node_modules/next/dist/next-server/server/api-utils.js
- /media/hoang/DEV/withstereo/node_modules/next/dist/next-server/server/next-server.js
- /media/hoang/DEV/withstereo/node_modules/next/dist/server/next.js
- /media/hoang/DEV/withstereo/bundle.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/media/hoang/DEV/withstereo/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js:20:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/media/hoang/DEV/withstereo/node_modules/next-with-apollo/node_modules/@apollo/react-ssr/lib/react-ssr.cjs.js:12:19)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/media/hoang/DEV/withstereo/node_modules/@apollo/react-hooks/lib/react-hooks.cjs.js',
    '/media/hoang/DEV/withstereo/node_modules/next-with-apollo/node_modules/@apollo/react-ssr/lib/react-ssr.cjs.js',
    '/media/hoang/DEV/withstereo/node_modules/next-with-apollo/lib/withApollo.js',
    '/media/hoang/DEV/withstereo/node_modules/next-with-apollo/lib/index.js',
    '/media/hoang/DEV/withstereo/.next/server/static/development/pages/_app.js',
    '/media/hoang/DEV/withstereo/node_modules/next/dist/next-server/server/load-components.js',
    '/media/hoang/DEV/withstereo/node_modules/next/dist/next-server/server/api-utils.js',
    '/media/hoang/DEV/withstereo/node_modules/next/dist/next-server/server/next-server.js',
    '/media/hoang/DEV/withstereo/node_modules/next/dist/server/next.js',
    '/media/hoang/DEV/withstereo/bundle.js'
  ]
}
```

Thank you!

**Comment by lfades** [comment]
@hoangvvo I've removed `@apollo/react-ssr` entirely, you can still add it (check the docs), but for the cases of apps that don't need SSR, the package will no longer included 😌
